credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "ubuntu-creds"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAowK6R+RL4Ys9XYvSH8p/EyW2uyScsrwuK0upU78ezyhkxlS76Xbf0cmlOakT2h/pdgST5VkJ/eX88/Nm6TN2m0ibgyek83dsq9pcJn4dF38sdfo+Ve9Qg3wYGHFTyKvv5jSjYzvhGjbVdS/HzNh05zheWL7XgTbVLhzori7C5yGegkBJeJOBIVEt/INiXVBsF/SXqWpfdrhNTaZu1uQU+SOj/p551EOBv6LPsik1PPJPYlD0FzA9KcPKbGdsg7HHMm+/ydsAzd37Dhn8n+j/Ii+gMaE0Rd1ZjFXOK8QJMaYAnkHKFMBD3xNSXkXlgHasKEj2RHu7yfoR7ZTuoMCsYpilCokP6w8yVSi9sonBDIzw5jPeY2CoqsU/WzlrWv4GKdsbm5dS7/wBaSDSmD3Fu9NBVB88ZiGvIqFUfX1jFC8BHtdPwGBNS8t1E3Br0CTOUNRBxPOe9Tl7s8M1eOEGvgfxUNxhjN3YjKgsKp6ArC/7ckYXJMXHGlw9abzONnLvTn9zFt5W8rXSGSFgLLrFZUc9P97XhZ/YCGxj7+sKKRBhXXr7dhfBRsmr5RSKUBTCujdxKrung1eb8cH/M2fWvFRL4gfLueLgR3SZ6rjfn7ioZQ5oM0sYAIfgv7R3ZMG2c7MhlzkyF1WqJOi8xJUcBWhPGPgg/wE8Vm3JCVlm931Mvuholim3MoFMhYtuj+QDmQuUvCr4vjekU+yfESNDMRdS/0Q3tgI0Js3EKxNX3Tu5mBbZmA5schXpCCR6Nu3Q5lmOdCk+Df1nE8VWAUQRHAkJ9X3U1bpfLHGrP9+7epJjUDUkgX0i3k0SABshr7R0OUoIN945xSwh/SEiahSEyJF5oppr7Z8E0OcikOTVAi7kVzdWZ0hU7HqeRcRzCWvlw6dh3peame8R/rEr46oQ3EhdBJkr2vvRb6qRN2JSYBgn1jaRBwpiDBR6RNDRDNk4gVgvvAjw2RIuSPmej3RaTOzMaTs2a1or9nDzTYFaFF14QfOUVGlix3XVBSQhzB2PWFWuni2uQQJ9GnUlusRhK+V8evsXYkR3xUM4A6Ir/fc42Z/Vb3KtLGEqRMO8B46eYeTAcgdlTvL47c8jzqcnHeui/hhdiIE4fV1QRBq0hQLCTpz6egqJScau1FiBZDu9yqlJabMDPVJUCMOILrcIAaOrGxEhLO+/VcLBhCOgm0C4y2i4mBKyhSQEw4EcahsWz25AYUjbO8EH9WYlnik1y/oHUcNNNkhlKf0YY+cuDq/vYxH0/UjR8tZVtSkNU0fTzBcZkz1CAaV6/a1QxxFWy4QImlrSIUMzqndhuSK1jIX5VAdQAKX2hbt5pwxXomxNMvWz2CKTD4wLKRngbcH5xc0sk6KJqT9+IEFsDu8N9ZUHT/9sHNOI/KjU1SuQlW2p/EurS5DuKkay4v8uOz9UQajqN+fdYbrJhMc5+N1hcCaT4aDEZsty63F4xJx0yPp/n0j1hY1jVpoP7Cu88WxECoEpOyscPF+rnL0zCvMIwaIHYiE/yqzLML6/RawIWmAlQuDboh6Q5NfDYqOWWavIxH7sDGR87sm7PLJi1uEZCPWqbmGIBl7JRsMfeZ5Vxi4F3eZnB8Fyjl7GoWHGIXS33or0dEwww1yi01NvpL5edeshN8zyV+o6UTA1JrGGSkqvew83JShckOYXp4G7ePH4hphHrj9PoSLHIJIi0aKwfUGIyC3QWXk4iqiyTH1GvGYJvhZnky/wCyZeRESQHaNRnLKHGFll3UbVHTkuOg+RJH9a0ZTRBq80ZaLjcgJfGPpv9sCYBXui9jb+jW0v4p2qB5X0Jdw1IOqCaCmx5qT6m0qnRhd7fZUqr2CNjp+rlm5Q6DwU0/n10BZRtYfK7s64vk5Qs3gBkUnvSMqFvtYCO3lZf78bYJauEp7A6n85VUkOXczbVGTfJLNqoM/aUJ4giB4FubpOFuJTfo873P6HaMBxa3CEN+DXbNIkP9+RV+9iaVGok/d6bGwdifYg5YLF95Qr9AVkyLYpeZrqm8sP3/d7uNdLrTNlFEL4s7kaW3A4etVugjJyRj4nK+5dgGK6AjtUW0IORb2sxa+tbLw70CBUI0P4oGS+Q6phdiPUOC7syiEAX9R73FHaQGQAbdkWqyWYNqoUzI82A3W6YAtsIHFJpKpUJUOb/PdnsM1H9nhWkwrLV2mFCA9CtIpXZ4Zss1w3hoAHTunGOPxt12vPaszyNwr0j4zNv9sZFcvwg5mtpC5J6EzLZMQzVD36w3SeiNHyO5zJ74OcHRQC8q95lfMGxSrlbWvfbgzn1EXX1+QSFatlo8LdIC4OnRmhmDUha2p65qG3fhc8jn6GzQqOKlqk37CyqTpl7U0xAYQE6nQekW6PcSOOENHtTDdGUlmcUkDk6HHVwZ4WYv2/XEUN/WYNpYftbaL758BUXlRygMSxzmHgihyM9ktHtl/10MwFR/hAlbIdJgu6wmBK3JCe7Z9gm3mYwD0oXN+/zIhcCpIPW3mCEgSWvZsBptF5KfcQ+b1NiPmCXN8nFx+L2D8pWw5lLUcB7VL6pLo/Udq79N6LwAkcMjAW8E/pmJaRX55Px7IWZ99CikmbSHliF6J4nAjzMGgYTWVN+qnwfWOsyB4kKE1/+hB08eOfntV6Je7oZFlW0PNZDs7XjCZm2YKlvez5OmPHNU/RqRFdzxRp38diwG7nRcgHKl+kycFQT7X9KD9ZVBWbyidoyWybfCKA02yJlSnu2cENV/9Ua4bbaYjIN4sy+aaPBUmc6KZXr6wjh3Bbln7WjgUahqBnvP71F2wp4VpI8pcY1M64plBqVr0b3fh6YijZvwMHVo/0ywqDmvX5OG4gwwMBHVL/NCUuTS5c+NO7oVxccS1CZ9144kUAqRGPMqBCHuEZ7QrvcShDi+/8uHewbE1lMPEe5R0eMwx6fj3BGek7CRPJW/YJ++oRrYhJkUpTIfXmxwYOetqlFMYRtZz5QwY9fzF+JQ83QBe2jNbuzn9t2vks/1CNqVDNLAMvINg28m1sV6f/7k3/4gWWVsYCq0wBScvCE0YujPuqi3VWbnoK8Fi6YwK7I4mi5G2GT3mnlEIFy0YEBuBjCGmlSJZhXRvF5lx5dUkWXP6KGkFnfskohb/68DYWYkUBEinSVOAAQyJYjoI+AO0tYaAeGT2+ICqMetFHevXxO2o6IvAO8BbRlnfYmP+fuV1y5x0AtP0xEcULahxH/Tz8jAm3j+0WD7fA3VrrrJ5+gffAX/uIcxrDqjKDbFkkigbiZ1FoL4mTiZ5N6rACqxsUuGJTy3Y3EfJky/dXnP0605sXsLx4HH7mv7f26wda6ZuVvzKiZLDyDwuE8nXTaNuvZUEu2uO5qo413Cgkr0dHy5B/k4lABYPxQJI7KJ/diFQCb/IWUiRyQhvCFTBLKSvwks6myKR0wX35BKUZCGAe0xQR5DZCDkWUF8SChgF1TEAbvZ5XV8kD/hMcbqw0/lT9De5ZCH3764t08LJMaMdjT7sxw=}"
          scope: GLOBAL
          username: "ubuntu"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "hudson.diagnosis.ReverseProxySetupMonitor"
  labelAtoms:
  - name: "built-in"
  - name: "controller"
  - name: "node1"
  labelString: "controller"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  nodes:
  - permanent:
      labelString: "node1"
      launcher:
        ssh:
          credentialsId: "ubuntu-creds"
          host: "10.0.1.178"
          port: 22
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: "node1"
      numExecutors: 5
      remoteFS: "/home/ubuntu/jenkins_node"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "artem"
        password: ${JENKINS_ADMIN_PASSWORD}
        name: "Artem Utkin"
        properties:
        - "myView"
        - "timezone"
        - "experimentalFlags"
        - "apiToken"
        - "mailer"
        - preferredProvider:
            providerId: "default"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubPluginConfig:
    hookUrl: "http://35.158.123.225:8080/github-webhook/"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://35.158.123.225:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - file: /usr/local/seedjob.groovy
